services:
  - type: web
    name: freefire-login-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: NEON_DB_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
